use_frameworks!

platform :ios, '8.0'

target 'JRouter_Example' do
  pod 'JRouter', :path => '../'

  target 'JRouter_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
