use_frameworks!

platform :ios, '10.0'

target 'JRouter_Example' do
  #pod 'JRouter', :path => '../'
	pod 'JRouter', :podspec => '../JRouter.podspec'

  target 'JRouter_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
